baseURL: "https://dmitriyvde.github.io/"
title: "Dmitriy Codes"
languageCode: "en-us"
theme: "m10c"
# sectionPagesMenu: "main"

# taxonomies as per Hugo's taxonomy feature
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

# menu as per Hugo's menu feature
# menu:
#   main:
    # - identifier: "home"
    #   name: "Home"
    #   url: "/"
    #   weight: 1
    # - identifier: "posts"
    #   name: "Posts"
    #   url: "/posts/"
    #   weight: 2
    # - identifier: "tags"
    #   name: "Tags"
    #   url: "/tags/"
    #   weight: 3
    # - identifier: "about"
    #   name: "About"
    #   url: "/about/"
    #   weight: 4

params:
  author: "Dmitriy Van der Elst"
  description: "A developer from Belgium with a passion for cool new tech, staying fit, and doing things like trying to teach people stuff."
  # avatar: "/assets/images/profile-dj-red.jpg"
  menu_item_separator: " - "
  # favicon: "/favicon.ico"
  social:
    - icon: "github"
      name: "My Github"
      url: "https://github.com/dmitriyvde"
